language: node_js
node_js:
  - "stable"
install:
  - yarn install
script:
  - yarn build
  - mv public/index.html public/200.html
deploy:
  provider: surge
  skip_cleanup: true
  project: ./public/
on:
  branch: master
