---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/blog
  label: Blog Posts
  create: documents
  match: "**/*.mdx"
  new_doc_ext: mdx
  templates:
  - blog-post
- type: directory
  path: content/pages
  label: Custom Pages
  create: documents
  match: "**/*.mdx"
  new_doc_ext: mdx
upload_dir: content/images
public_path: "/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
